#!/usr/bin/env sh

# Shell script that displays configured keyboard shortcuts

echo "⌨⌨⌨ SHORTCUTS ⌨⌨⌨"
echo
echo "ALIASES"
echo "sc"
echo "shortcut"
echo "shortcuts"
echo "kbs"
echo "kbsc"
echo "hotkey"
echo "hotkeys"
echo
echo

cat << 'TABLE'
|---------------------------------------------------------------------|
| MISC.                                                               |
|---------------------------------------------------------------------|
| FUNCTION                         | SHORTCUT                         |
|---------------------------------------------------------------------|
| Open Terminal                    | Super + Enter                    |
| Open File Explorer               | Super + F                        |
| Open Web Browser                 | Super + W                        |
| Open Emoji Picker                | Ctrl  + Shift + E, Ctrl + .      |
| xkill                            | Ctrl  + Alt + Esc                |
|---------------------------------------------------------------------|
TABLE

echo
echo

cat << 'TABLE'
|---------------------------------------------------------------------|
| OBSIDIAN                                                            |
|---------------------------------------------------------------------|
| FUNCTION                         | SHORTCUT                         |
|---------------------------------------------------------------------|
| Delete a Paragraph               | Ctrl + D                         |
| Open Graph View                  | Ctrl + G                         |
| Insert Markdown Link             | Ctrl + K                         |
| Toggle Numbered List             | Alt  + L                         |
| Toggle Unordered List            | Ctrl + Alt + L, Ctrl + Shift + L |
| Toggle Checklist                 | Ctrl + L                         |
| Toggle Checkbox Status           | Ctrl + L                         |
| Toggle Highlight                 | Ctrl + Shift + H                 |
| Toggle Comment                   | Ctrl + /                         |
| Toggle Quote                     | Ctrl + Shift + Q                 |
|---------------------------------------------------------------------|
TABLE

echo
echo

cat << 'TABLE'
|---------------------------------------------------------------------|
| BROWSER SEARCH ENGINES                                              |
|---------------------------------------------------------------------|
| SEARCH ENGINE                    | SHORTCUT                         |
|---------------------------------------------------------------------|
| Search Engines                   | se                               |
| xAI                              | ai                               |
| AUR                              | aur                              |
| AlternativeTo                    | at                               |
| Amazon                           | a                                |
| Arch Packages                    | ap, pacman, pack                 |
| ArchWiki                         | aw, awiki, arch                  |
| Bookmarks                        | @bookmarks                       |
| Chrome Web Store                 | cws                              |
| Copilot                          | cp                               |
| cheat.sh                         | cheat.sh                         |
| DuckDuckGo Lite                  | ddgl                             |
| ddgtty                           | ddgtty                           |
| getemoji.com                     | e                                |
| Emoji Combos                     | ec, emo                          |
| ETFDB                            | etf                              |
| F-Droid                          | fd, fdroid                       |
| Fidelity                         | f                                |
| Gemini                           | @gemini                          |
| Giphy                            | gif                              |
| Gist                             | gist                             |
| GitHub                           | gh                               |
| Google AI Mode                   | @aimode                          |
| Google Drive                     | gd                               |
| Google Maps                      | map                              |
| Grok                             | grok                             |
| Hacker News                      | hn                               |
| History                          | @history                         |
| HuggingFace                      | hf                               |
| Instagram                        | i                                |
| Internet Archive                 | archive                          |
| Kalshi                           | k                                |
| Newegg                           | ne                               |
| nostr                            | nostr                            |
| npm                              | npm                              |
| pip                              | pip                              |
| Page                             | @page                            |
| Play Store                       | ps                               |
| Primal                           | p                                |
| PyPI                             | pypi                             |
| Reddit                           | r                                |
| Spotfiy                          | spot                             |
| Startpage                        | sp                               |
| Tabs                             | @tabs                            |
| TradiingView                     | tv                               |
| Twitch                           | tw                               |
| Twitter                          | t                                |
| X                                | x                                |
| Wikipedia                        | w                                |
| Yeggi                            | yeggi                            |
| YouTube                          | yt                               |
| YouTube Music                    | ytm                              |
|---------------------------------------------------------------------|
TABLE

echo

